name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_SECRET_KEY }}
            HOSTNAME: ${{secrets.SERVER_IP}}
            USER_NAME: ${{secrets.SERVER_USER}}
      
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /root/backend_stage &&
              git checkout main &&
              git pull origin main &&
              sudo npm i &&
              sudo npm run build &&
              sudo pm2 restart backend_stage
              '